config/routes.rb
Rails.application.routes.draw do
  
  
  
  
  
  
  

  get 'recent' => "articles#recents",as: :recent_article
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article= Article.find params[:id]
    end
    def index
        @articles=Article.all
    end
    def create
        @article=Article.new(params.require(:article).permit(:title, :content))
        #e chưa hiểu chỗ này
        # Cái này để tạo một article mới với title, content được lấy từ  form mà mình điền
        @article.save
        redirect_to article_path(@article)
        #e chưa hiểu chỗ này
        # Cai nay de chuyen trang den show, trong routes co "get "articles/:id" => "artcicles#show", as: :show_article
    end
    def destroy
        @article= Article.find params[:id]
        @article.destroy
        redirect_to :back
    end
    def edit
        @article= Article.find params[:id]
    end
    def update
        @article= Article.find params[:id]
        @article.update_attributes params.require(:article).permit(:title, :content)
        # Cái này để tạo một article thay thế khi mình edit , với title, content được lấy từ  form mà mình điền
        redirect_to article_path(@article)
        # Cai nay de chuyen trang den show, trong routes co "get "articles/:id" => "artcicles#show", as: :show_article
    end
    def new
        @article=Article.new
    end
    def recents
        @recent_article=Article.last(5)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/edit.html.erb
<%#= form_for :article, url: "/articles", method: :post do |f| %>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
<!--trong routes có 1 as: :show_article-->
<!--vs cả có 1 cái patch "articles/:id"-->
<!--nên trong form vs method: :patch, url là show_article_path thì khi submit nó sẽ chạy vào hàm update trong controller-->
    <%= f.label :Title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :content %> 
    <%= f.text_area :content, class: "form-control", rows: 2 %>
    <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
<% end %>

app/views/articles/index.html.erb
<%= link_to "Add a article", new_article_path, class: "btn btn-success" %> 
<hr>
<% @articles.each do |article| %>
  <div>
    <h2><%= article.title %></h2>
    <p>
      <%= link_to "Edit", edit_article_path(article), class:"text-muted action-link" %>
      <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class:"text-muted action-link" %>
      <span class="pull-right text-muted">
        <%= article.created_at.strftime("%B - %d - %Y") %>, posted by <a href="#">Thắng</a>
      </span>
    </p>
    <p><%= article.content.first(1000) %></p>
    <%= link_to "Read more ...", article_path(article) %></br>
    <%= social_share_button_tag(article.title, url: article_url(article), :popup => "true") %>
  </div>
<% end %>

app/views/articles/new.html.erb
<%#= form_for :article, url: "/articles", method: :post do |f| %>
<%= form_for :article, url: articles_path, method: :post do |f| %>
<!--trong routes có 1 as: :show_article-->
<!--vs cả có 1 cái patch "articles/:id"-->
<!--nên trong form vs method: :patch, url là show_article_path thì khi submit nó sẽ chạy vào hàm update trong controller-->
    <%= f.label :Title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :content %> 
    <%= f.text_area :content, class: "form-control", rows: 2 %>
    <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
<% end %>

app/views/articles/recents.html.erb
<%= link_to "Add a article", new_article_path, class: "btn btn-success" %> 
<hr>
<% @recent_article.each do |article| %>
  <div>
    <h2><%= article.title %></h2>
    <p>
      <%= link_to "Edit", edit_article_path(article), class:"text-muted action-link" %>
      <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class:"text-muted action-link" %>
      <span class="pull-right text-muted">
        <%= article.created_at.strftime("%B - %d - %Y") %>, posted by <a href="#">Thuc</a>
      </span>
    </p>
    <p><%= article.content.first(1000) %></p>
    <%= link_to "Read more ...", article_path(article) %></br>
  </div>
<% end %>

app/views/articles/show.html.erb
Tieu de: <%= @article.title %>
Noi dung: <%= @article.content %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="header">      
  </header>

  <div class="container-fluid">
    <div class="row content">
      <div class="col-sm-3 sidenav">
        <h4>thang Blog</h4>
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#section1">Home</a></li>
          <li><a href="#section2">Friends</a></li>
          <li><a href="#section3">Family</a></li>
          <li><a href="#section3">Photos</a></li>
        </ul><br>
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search Blog..">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      </div>
      <div class="col-sm-9" id="main-content">
        <%= flash[:alert] %></br>
        <%= yield %>
      </div>
    </div>
  </div>
</body>

</html>